apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-api
  name: nginx-api
spec:
  ports:
  - name: "9100"
    port: 9100
    targetPort: 443
  selector:
    io.kompose.service: nginx-api
status:
  loadBalancer: {}
