apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-pv
  hostPath:
    path: /data/postgres
